const fs = require('fs-extra');
const path = require('node:path');
const chalk = require('chalk');

/**
 * CPM (Cinematic Production Module) Installer
 *
 * Scaffolds new CPM projects with the complete directory structure
 * and template files for AI video production workflows.
 */
async function install(options) {
  const { projectRoot, config, installedIDEs, logger } = options;

  try {
    logger.log(chalk.blue('Installing CPM: Cinematic Production Module...'));

    // Get the templates directory (relative to this installer)
    const templatesDir = path.join(__dirname, '..', 'templates', 'project');

    // Determine output location
    const cpmOutputFolder = config['cpm_output_folder']
      ? config['cpm_output_folder'].replace('{project-root}/', '')
      : '_bmad-output/cpm-projects';

    // Create the CPM project structure
    await createProjectStructure(projectRoot, cpmOutputFolder, config, logger);

    // Copy template files
    await copyTemplates(projectRoot, templatesDir, logger);

    // Create config.yaml with user settings
    await createProjectConfig(projectRoot, config, logger);

    // IDE-specific configuration
    if (installedIDEs && installedIDEs.length > 0) {
      for (const ide of installedIDEs) {
        await configureForIDE(ide, projectRoot, config, logger);
      }
    }

    logger.log(chalk.green('✓ CPM installation complete'));
    logger.log(chalk.cyan('\nNext steps:'));
    logger.log(chalk.cyan('  1. Run /cpm to start the Shard Generation Ritual'));
    logger.log(chalk.cyan('  2. Or create a new project with /cpm-new-project'));

    return true;
  } catch (error) {
    logger.error(chalk.red(`Error installing CPM module: ${error.message}`));
    return false;
  }
}

/**
 * Create the CPM project directory structure
 */
async function createProjectStructure(projectRoot, outputFolder, config, logger) {
  const directories = [
    // Core CPM folders
    '.cpm',
    '.cpm/agents',

    // Bible (Story)
    'Bible',
    'Bible/Characters',
    'Bible/World',

    // Architecture (Visual)
    'Architecture',

    // Production (Active Work)
    'Production',
    'Production/Scenes',
    'Production/Contracts',

    // Output (Generated)
    'Output',
    'Output/Prompts',
    'Output/Renders'
  ];

  for (const dir of directories) {
    const dirPath = path.join(projectRoot, outputFolder, dir);
    if (!(await fs.pathExists(dirPath))) {
      logger.log(chalk.yellow(`Creating: ${outputFolder}/${dir}/`));
      await fs.ensureDir(dirPath);
    }
  }
}

/**
 * Copy template files to the project
 */
async function copyTemplates(projectRoot, templatesDir, logger) {
  // Check if templates exist
  if (!(await fs.pathExists(templatesDir))) {
    logger.warn(chalk.yellow('Templates directory not found. Skipping template copy.'));
    return;
  }

  // Template files will be copied by the scaffold workflow
  // This installer just ensures the structure exists
  logger.log(chalk.blue('Template structure ready for project scaffolding.'));
}

/**
 * Create project config.yaml with user settings
 */
async function createProjectConfig(projectRoot, config, logger) {
  const projectName = config['project_name'] || 'Untitled Project';
  const modelTarget = config['model_target'] || 'wan';
  const shardDuration = config['default_shard_duration'] || '5';
  const strictValidation = config['enable_strict_validation'] !== false;

  const configContent = `# CPM Project Configuration
# Generated by CPM Module Installer

project_name: "${projectName}"
version: "1.0"
created: "${new Date().toISOString().split('T')[0]}"

# Production Settings
temporal:
  default_shard_duration: ${shardDuration}  # seconds
  max_shard_duration: 30

# Model Target
model:
  target: "${modelTarget}"  # wan | sora | kling | runway | other

# Agent Settings
agents:
  showrunner:
    enabled: true
    prompt_file: ".cpm/agents/showrunner.md"
  cinematographer:
    enabled: true
    prompt_file: ".cpm/agents/cinematographer.md"
  script_supervisor:
    enabled: true
    prompt_file: ".cpm/agents/script-supervisor.md"
  prompt_engineer:
    enabled: true
    prompt_file: ".cpm/agents/prompt-engineer.md"

# Validation Rules
validation:
  require_state_diff_check: ${strictValidation}
  require_style_compliance: ${strictValidation}
  banned_words_enforcement: ${strictValidation}
`;

  // Note: This config is a template - actual project config created by scaffold workflow
  logger.log(chalk.blue('Project configuration template ready.'));
}

/**
 * IDE-specific configuration
 */
async function configureForIDE(ide, projectRoot, config, logger) {
  const platformSpecificPath = path.join(__dirname, 'platform-specifics', `${ide}.js`);

  try {
    if (await fs.pathExists(platformSpecificPath)) {
      const platformHandler = require(platformSpecificPath);
      if (typeof platformHandler.install === 'function') {
        await platformHandler.install({ projectRoot, config, logger });
      }
    }
  } catch (error) {
    logger.warn(chalk.yellow(`Warning: Could not configure ${ide}: ${error.message}`));
  }
}

module.exports = { install };
